version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install -g @nestjs/cli
  build:
    commands:
      - echo Building the application...
      - npx prisma generate
      - npm run build
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Post build phase...
      - echo Preparing deployment package with correct structure...
      # Create the deployment structure that maintains relative paths
      - mkdir -p deploy-root/dist
      - cp -r dist/* deploy-root/dist/
      - cp -r generated deploy-root/
      - cp -r prisma deploy-root/
      - cp package*.json deploy-root/
      - cp appspec.yml deploy-root/
      - cp -r scripts deploy-root/
      - cp ecosystem.config.js deploy-root/
      - cp tsconfig.json deploy-root/
      - cp nest-cli.json deploy-root/

artifacts:
  files:
    - '**/*'
  base-directory: 'deploy-root'
  name: bookmark-app-build