version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install -g @nestjs/cli
  build:
    commands:
      - echo Building the application...
      - npx prisma generate
      - npm run build
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Post build phase...
      - cp package*.json dist/
      - cp -r prisma dist/
      - cp -r generated dist/ || echo "Generated folder will be created during deployment"
      - cp appspec.yml dist/
      - cp -r scripts dist/
      - cp ecosystem.config.js dist/
      - cp tsconfig.json dist/
      - cp nest-cli.json dist/

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  name: bookmark-app-build